package com.herinoid.rsi.gui;

import com.herinoid.rsi.dao.DataProlanisDao;
import com.herinoid.rsi.model.DataProlanis;
import com.herinoid.rsi.model.ProlanisDetail;
import com.herinoid.rsi.table.DefaultTableCellRender;
import com.herinoid.rsi.table.TabelProlanis;
import com.herinoid.rsi.table.TabelProlanisDetail;
import com.herinoid.rsi.util.Utils;
import java.util.Date;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class DlgDataProlanisPasien extends javax.swing.JDialog {
    private  TabelProlanis modelProlanis;
    private TabelProlanisDetail modelDetail;

    /**
     * Creates new form DlgProgramStudi
     *
     * @param parent
     * @param modal
     */
    public DlgDataProlanisPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelProlanis = new TabelProlanis(DataProlanisDao.getDataProlanisByTanggal(Utils.formatDb(Utils.getFirstDayInMonth(new Date())), Utils.formatDb(Utils.getLastDayInMonth(new Date()))));
        modelDetail = new TabelProlanisDetail();
        tblProlanis.setModel(modelProlanis);
        tblDetail.setModel(modelDetail);
        for (int i = 0; i < tblProlanis.getColumnCount(); i++) {
            tblProlanis.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
        for (int i = 0; i < tblDetail.getColumnCount(); i++) {
            tblDetail.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
        
        tblProlanis.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int selected = tblProlanis.getSelectedRow();
                if (selected != -1) {
                    DataProlanis pro = modelProlanis.getList().get(selected);
                    List<ProlanisDetail> list = pro.getProlanisDetails();
                    modelDetail.setList(list);
                }
            }
        });
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelisi2 = new widget.panelisi();
        panelisi4 = new widget.panelisi();
        scrollPane1 = new widget.ScrollPane();
        tblProlanis = new widget.Table();
        panelisi5 = new widget.panelisi();
        scrollPane2 = new widget.ScrollPane();
        tblDetail = new widget.Table();
        panelisi3 = new widget.panelisi();
        label16 = new widget.Label();
        label17 = new widget.Label();
        fromDate = new widget.Tanggal();
        Tgl2 = new widget.Tanggal();
        toDate = new widget.Tanggal();
        btncari = new widget.Button();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Rekap Data Prolanis Pasien  ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi2.setName("panelisi2"); // NOI18N
        panelisi2.setLayout(new java.awt.GridLayout(2, 1));

        panelisi4.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Prolanis Pasien"));
        panelisi4.setName("panelisi4"); // NOI18N
        panelisi4.setLayout(new javax.swing.BoxLayout(panelisi4, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane1.setName("scrollPane1"); // NOI18N

        tblProlanis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProlanis.setName("tblProlanis"); // NOI18N
        scrollPane1.setViewportView(tblProlanis);

        panelisi4.add(scrollPane1);

        panelisi2.add(panelisi4);

        panelisi5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Prolanis Pasien"));
        panelisi5.setName("panelisi5"); // NOI18N
        panelisi5.setLayout(new javax.swing.BoxLayout(panelisi5, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane2.setName("scrollPane2"); // NOI18N

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setName("tblDetail"); // NOI18N
        scrollPane2.setViewportView(tblDetail);

        panelisi5.add(scrollPane2);

        panelisi2.add(panelisi5);

        internalFrame1.add(panelisi2, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(619, 45));
        panelisi3.setWarnaAtas(new java.awt.Color(255, 0, 153));
        panelisi3.setWarnaBawah(new java.awt.Color(255, 102, 255));
        panelisi3.setLayout(null);

        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label16.setText("S/D");
        label16.setName("label16"); // NOI18N
        label16.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label16);
        label16.setBounds(180, 10, 30, 23);

        label17.setForeground(new java.awt.Color(255, 255, 255));
        label17.setText("Periode :");
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label17);
        label17.setBounds(0, 10, 75, 23);

        fromDate.setDisplayFormat("dd-MM-yyyy");
        fromDate.setName("fromDate"); // NOI18N
        fromDate.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi3.add(fromDate);
        fromDate.setBounds(80, 10, 95, 23);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi3.add(Tgl2);
        Tgl2.setBounds(80, 10, 95, 23);

        toDate.setDisplayFormat("dd-MM-yyyy");
        toDate.setName("toDate"); // NOI18N
        toDate.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi3.add(toDate);
        toDate.setBounds(220, 10, 95, 23);

        btncari.setBackground(new java.awt.Color(255, 255, 255));
        btncari.setBorder(null);
        btncari.setForeground(new java.awt.Color(255, 255, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search.png"))); // NOI18N
        btncari.setText("Cari");
        btncari.setName("btncari"); // NOI18N
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        panelisi3.add(btncari);
        btncari.setBounds(333, 10, 100, 25);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setWarnaAtas(new java.awt.Color(255, 51, 255));
        panelisi1.setWarnaBawah(new java.awt.Color(255, 0, 153));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 9));

        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        modelProlanis = new TabelProlanis(DataProlanisDao.getDataProlanisByTanggal(Utils.formatDb(Utils.getFirstDayInMonth(fromDate.getDate())), Utils.formatDb(Utils.getLastDayInMonth(toDate.getDate()))));
        modelDetail = new TabelProlanisDetail();
        tblProlanis.setModel(modelProlanis);
        tblDetail.setModel(modelDetail);
        for (int i = 0; i < tblProlanis.getColumnCount(); i++) {
            tblProlanis.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
        for (int i = 0; i < tblDetail.getColumnCount(); i++) {
            tblDetail.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgDataProlanisPasien dialog = new DlgDataProlanisPasien(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Tanggal Tgl2;
    private widget.Button btncari;
    private widget.Tanggal fromDate;
    private widget.InternalFrame internalFrame1;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.panelisi panelisi2;
    private widget.panelisi panelisi3;
    private widget.panelisi panelisi4;
    private widget.panelisi panelisi5;
    private widget.ScrollPane scrollPane1;
    private widget.ScrollPane scrollPane2;
    private widget.Table tblDetail;
    private widget.Table tblProlanis;
    private widget.Tanggal toDate;
    // End of variables declaration//GEN-END:variables

}
