package com.herinoid.rsi.gui;

import com.herinoid.rsi.dao.GambarRadiologiDao;
import com.herinoid.rsi.dao.RekapPembelianObatDAO;
import com.herinoid.rsi.model.GambarRadiologi;
import com.herinoid.rsi.model.RekapPembelianObat;
import com.herinoid.rsi.table.DefaultTableCellRender;
import com.herinoid.rsi.table.TabelGambarRadiologi;
import com.herinoid.rsi.table.TabelRekapPembelianObat;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;

public class DlgRekapPembelianLangsung extends javax.swing.JDialog {

//    private List<GambarRadiologi> gambarRadiologis;
    private TabelRekapPembelianObat modelObat;

    /**
     * Creates new form DlgProgramStudi
     *
     * @param parent
     * @param modal
     */
    public DlgRekapPembelianLangsung(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        gambarRadiologis = new LinkedList<>();
        modelObat = new TabelRekapPembelianObat();
    }

    public void setData(List<RekapPembelianObat> rekapPembelianObats) {        
        modelObat.removeAllElements();
        modelObat.add(new HashSet<>(rekapPembelianObats));
        tableRekap.setModel(modelObat);
        for (int i = 0; i < tableRekap.getColumnCount(); i++) {
            tableRekap.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        scrollPane1 = new widget.ScrollPane();
        tableRekap = new widget.Table();
        panelisi3 = new widget.panelisi();
        label16 = new widget.Label();
        label17 = new widget.Label();
        fromDate = new widget.Tanggal();
        Tgl2 = new widget.Tanggal();
        toDate = new widget.Tanggal();
        btncari = new widget.Button();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Rekap Pembelian Langsung ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tableRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableRekap.setName("tableRekap"); // NOI18N
        scrollPane1.setViewportView(tableRekap);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(619, 45));
        panelisi3.setWarnaAtas(new java.awt.Color(255, 0, 153));
        panelisi3.setWarnaBawah(new java.awt.Color(255, 102, 255));
        panelisi3.setLayout(null);

        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label16.setText("S/D");
        label16.setName("label16"); // NOI18N
        label16.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label16);
        label16.setBounds(180, 10, 30, 23);

        label17.setForeground(new java.awt.Color(255, 255, 255));
        label17.setText("Periode :");
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label17);
        label17.setBounds(0, 10, 75, 23);

        fromDate.setDisplayFormat("dd-MM-yyyy");
        fromDate.setName("fromDate"); // NOI18N
        fromDate.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi3.add(fromDate);
        fromDate.setBounds(80, 10, 95, 23);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi3.add(Tgl2);
        Tgl2.setBounds(80, 10, 95, 23);

        toDate.setDisplayFormat("dd-MM-yyyy");
        toDate.setName("toDate"); // NOI18N
        toDate.setPreferredSize(new java.awt.Dimension(95, 23));
        panelisi3.add(toDate);
        toDate.setBounds(220, 10, 95, 23);

        btncari.setBackground(new java.awt.Color(255, 255, 255));
        btncari.setBorder(null);
        btncari.setForeground(new java.awt.Color(255, 255, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search.png"))); // NOI18N
        btncari.setText("Cari");
        btncari.setName("btncari"); // NOI18N
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        panelisi3.add(btncari);
        btncari.setBounds(333, 10, 100, 25);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setWarnaAtas(new java.awt.Color(255, 51, 255));
        panelisi1.setWarnaBawah(new java.awt.Color(255, 0, 153));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 9));

        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        List<RekapPembelianObat> rekaps = RekapPembelianObatDAO.getPembelianByPeriode(fromDate.getDate(), toDate.getDate());
        modelObat.removeAllElements();
        modelObat.add(new HashSet<>(rekaps));
        tableRekap.setModel(modelObat);
        for (int i = 0; i < tableRekap.getColumnCount(); i++) {
            tableRekap.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRekapPembelianLangsung dialog = new DlgRekapPembelianLangsung(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Tanggal Tgl2;
    private widget.Button btncari;
    private widget.Tanggal fromDate;
    private widget.InternalFrame internalFrame1;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.panelisi panelisi3;
    private widget.ScrollPane scrollPane1;
    private widget.Table tableRekap;
    private widget.Tanggal toDate;
    // End of variables declaration//GEN-END:variables

}
