package com.herinoid.rsi.gui;

import com.herinoid.rsi.dao.BillingRanapDAO;
import static com.herinoid.rsi.dao.BillingRanapDAO.getKamarInap;
import com.herinoid.rsi.model.BillingRanap;
import com.herinoid.rsi.model.BillingSimulator;
import com.herinoid.rsi.model.KamarInap;
import com.herinoid.rsi.table.DefaultTableCellRender;
import com.herinoid.rsi.table.TabelBillingSimulator;
import com.herinoid.rsi.util.Kelas;
import java.util.Set;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class DlgSimulasiBilling extends javax.swing.JDialog {

    private TabelBillingSimulator modelBiling;
    private Set<BillingSimulator> kelasSekarangList;
    private Set<BillingSimulator> kelasAtasnyaList;
    private Set<BillingSimulator> kelasBawahnyaList;
    private String noRawat;
    private String kelasNow;

    /**
     * Creates new form DlgProgramStudi
     *
     * @param parent
     * @param modal
     */
    public DlgSimulasiBilling(java.awt.Frame parent, boolean modal, String norawat) {
        super(parent, modal);
        this.noRawat = norawat;
        initComponents();
        modelBiling = new TabelBillingSimulator();
        initData(norawat);
        BillingRanap bilRanap = BillingRanapDAO.getRegistrasiPasien(norawat);
        kelasNow = bilRanap.getKelas();
        lblNoNota.setText(bilRanap.getNoNota());
        lblBangsal.setText(bilRanap.getNamaBangsal());
        txtRm.setText(bilRanap.getNorm());
        lblNamaPasien.setText(bilRanap.getNamaPasien());
        lblAlamat.setText(bilRanap.getAlamat());
        lblTglPerawatan.setText(bilRanap.getTglPerawatan());
        changeHeaderTitle();
    }

    private void initData(String norawat) {
        modelBiling.removeAllElements();
        modelBiling.add(BillingRanapDAO.getBilingKelasSekarang(norawat,cboKelas.getSelectedItem().toString()));
        tblBilling.setModel(modelBiling);
        tblBilling.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblBilling.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        for (int i = 0; i < tblBilling.getColumnCount(); i++) {
            tblBilling.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
            tblBilling.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            tblBilling.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            tblBilling.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            tblBilling.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            tblBilling.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
            tblBilling.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblBilling.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblBilling.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblBilling.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblBilling.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblBilling.getColumnModel().getColumn(5).setPreferredWidth(200);
        }
        
    }

    private void changeHeaderTitle() {
        JTableHeader header = tblBilling.getTableHeader();
        TableColumnModel colMod = header.getColumnModel();
        TableColumn tabCol = colMod.getColumn(3);
        TableColumn tabPembading = colMod.getColumn(4);
        tabCol.setHeaderValue(kelasNow);
        tabPembading.setHeaderValue(cboKelas.getSelectedItem().toString());
        header.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelisi2 = new widget.panelisi();
        scrollPane4 = new widget.ScrollPane();
        tblBilling = new widget.Table();
        panelisi3 = new widget.panelisi();
        label16 = new widget.Label();
        txtRm = new widget.Label();
        label18 = new widget.Label();
        lblNoNota = new widget.Label();
        label19 = new widget.Label();
        lblBangsal = new widget.Label();
        label17 = new widget.Label();
        lblNamaPasien = new widget.Label();
        label20 = new widget.Label();
        lblTglPerawatan = new widget.Label();
        label21 = new widget.Label();
        lblAlamat = new widget.Label();
        panelisi1 = new widget.panelisi();
        label1 = new widget.Label();
        cboKelas = new widget.ComboBox();
        button1 = new widget.Button();
        label9 = new widget.Label();
        button2 = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Simulasi Billing Pasien  ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi2.setName("panelisi2"); // NOI18N
        panelisi2.setLayout(new javax.swing.BoxLayout(panelisi2, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane4.setName("scrollPane4"); // NOI18N

        tblBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBilling.setName("tblBilling"); // NOI18N
        scrollPane4.setViewportView(tblBilling);

        panelisi2.add(scrollPane4);

        internalFrame1.add(panelisi2, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(835, 109));
        panelisi3.setWarnaAtas(new java.awt.Color(0, 153, 153));
        panelisi3.setWarnaBawah(new java.awt.Color(0, 255, 204));
        panelisi3.setLayout(null);

        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setText("No. Rekam Medis :");
        label16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label16.setName("label16"); // NOI18N
        label16.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label16);
        label16.setBounds(0, 40, 140, 23);

        txtRm.setForeground(new java.awt.Color(255, 255, 255));
        txtRm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtRm.setText("txt");
        txtRm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRm.setName("txtRm"); // NOI18N
        txtRm.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(txtRm);
        txtRm.setBounds(160, 40, 140, 23);

        label18.setForeground(new java.awt.Color(255, 255, 255));
        label18.setText("No. Nota :");
        label18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label18);
        label18.setBounds(20, 10, 120, 23);

        lblNoNota.setForeground(new java.awt.Color(255, 255, 255));
        lblNoNota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNoNota.setText("txt");
        lblNoNota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNoNota.setName("lblNoNota"); // NOI18N
        lblNoNota.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblNoNota);
        lblNoNota.setBounds(160, 10, 140, 23);

        label19.setForeground(new java.awt.Color(255, 255, 255));
        label19.setText("Kamar :");
        label19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label19.setName("label19"); // NOI18N
        label19.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label19);
        label19.setBounds(20, 70, 120, 23);

        lblBangsal.setForeground(new java.awt.Color(255, 255, 255));
        lblBangsal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBangsal.setText("txt");
        lblBangsal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBangsal.setName("lblBangsal"); // NOI18N
        lblBangsal.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblBangsal);
        lblBangsal.setBounds(160, 70, 170, 23);

        label17.setForeground(new java.awt.Color(255, 255, 255));
        label17.setText("Nama Pasien :");
        label17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label17);
        label17.setBounds(350, 10, 110, 23);

        lblNamaPasien.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaPasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNamaPasien.setText("txt");
        lblNamaPasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamaPasien.setName("lblNamaPasien"); // NOI18N
        lblNamaPasien.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblNamaPasien);
        lblNamaPasien.setBounds(480, 10, 360, 23);

        label20.setForeground(new java.awt.Color(255, 255, 255));
        label20.setText("Tgl. Perawatan :");
        label20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label20.setName("label20"); // NOI18N
        label20.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label20);
        label20.setBounds(350, 40, 110, 23);

        lblTglPerawatan.setForeground(new java.awt.Color(255, 255, 255));
        lblTglPerawatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTglPerawatan.setText("txt");
        lblTglPerawatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTglPerawatan.setName("lblTglPerawatan"); // NOI18N
        lblTglPerawatan.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblTglPerawatan);
        lblTglPerawatan.setBounds(480, 40, 420, 23);

        label21.setForeground(new java.awt.Color(255, 255, 255));
        label21.setText("Alamat : ");
        label21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label21.setName("label21"); // NOI18N
        label21.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label21);
        label21.setBounds(370, 70, 90, 23);

        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlamat.setText("txt");
        lblAlamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAlamat.setName("lblAlamat"); // NOI18N
        lblAlamat.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(lblAlamat);
        lblAlamat.setBounds(480, 70, 420, 23);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setWarnaAtas(new java.awt.Color(0, 255, 204));
        panelisi1.setWarnaBawah(new java.awt.Color(0, 153, 153));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 9));

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Pilih Kelas : ");
        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setName("label1"); // NOI18N
        panelisi1.add(label1);

        cboKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kelas VVIP", "Kelas VIP", "Kelas 1", "Kelas 2", "Kelas 3" }));
        cboKelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboKelas.setName("cboKelas"); // NOI18N
        panelisi1.add(cboKelas);

        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Preview.png"))); // NOI18N
        button1.setText("Cari");
        button1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button1.setName("button1"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelisi1.add(button1);

        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(400, 30));
        panelisi1.add(label9);

        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PrinterSettings.png"))); // NOI18N
        button2.setText("Print");
        button2.setName("button2"); // NOI18N
        panelisi1.add(button2);

        BtnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        modelBiling.removeAllElements();
        modelBiling.add(BillingRanapDAO.getBilingKelasSekarang(noRawat,cboKelas.getSelectedItem().toString()));
        tblBilling.setModel(modelBiling);
        tblBilling.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        changeHeaderTitle();
        for (int i = 0; i < modelBiling.getColumnCount(); i++) {
            tblBilling.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
            tblBilling.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
            tblBilling.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
            tblBilling.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            tblBilling.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            tblBilling.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
            tblBilling.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblBilling.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblBilling.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblBilling.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblBilling.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblBilling.getColumnModel().getColumn(5).setPreferredWidth(200);
        }
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgSimulasiBilling dialog = new DlgSimulasiBilling(new javax.swing.JFrame(), true, "");
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button button1;
    private widget.Button button2;
    private widget.ComboBox cboKelas;
    private widget.InternalFrame internalFrame1;
    private widget.Label label1;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label18;
    private widget.Label label19;
    private widget.Label label20;
    private widget.Label label21;
    private widget.Label label9;
    private widget.Label lblAlamat;
    private widget.Label lblBangsal;
    private widget.Label lblNamaPasien;
    private widget.Label lblNoNota;
    private widget.Label lblTglPerawatan;
    private widget.panelisi panelisi1;
    private widget.panelisi panelisi2;
    private widget.panelisi panelisi3;
    private widget.ScrollPane scrollPane4;
    private widget.Table tblBilling;
    private widget.Label txtRm;
    // End of variables declaration//GEN-END:variables

}
