/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.herinoid.rsi.gui.dialog;

import com.herinoid.rsi.dao.MetodeRacikanDao;
import com.herinoid.rsi.model.MetodeRacikan;
import com.herinoid.rsi.model.Obat;
import com.herinoid.rsi.model.ObatResep;
import com.herinoid.rsi.widget.KeySelectionRenderer;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import widget.ComboBox;

/**
 *
 * @author Hewrei
 */
public class DialogRacikanResep extends javax.swing.JDialog {

    private ObatResep obatResep;
    private int countCode;
    private boolean isEdit;
    private boolean isTmp;

    /**
     * Creates new form DialogAddQtyResepDokter
     */
    public DialogRacikanResep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setPreferredSize(new Dimension(524, 327));
        setLocationRelativeTo(null);
        obatResep = new ObatResep();
        isEdit = false;
        setComboList();

    }

    public void setData(int count,boolean temp) {
        this.isTmp = temp;
        this.countCode = count;
        txtNamaRacikan.setText("Racikan " + count);
        obatResep = new ObatResep();
        isEdit = false;
    }
    
    public void setEditData(ObatResep obatR) {
        txtNamaRacikan.setText(obatR.getNamaObat());
        txtJumlah.setText(String.valueOf((int)obatR.getJumlah()));
        txtAturanPakai.setText(obatR.getAturanPakai());
        MetodeRacikan metod = new MetodeRacikan();
        metod.setKode(obatR.getMetodeRacikKode());
        metod.setMetode(obatR.getMetodeRacik());
        cmbRacikan.setSelectedItem(metod);
        obatResep = obatR;
        isEdit = true;
    }

    private void setComboList() {
        List<MetodeRacikan> metodes = MetodeRacikanDao.getAllMetode();
        for (MetodeRacikan m : metodes) {
            cmbRacikan.addItem(m);
        }
        KeySelectionRenderer renderer = new KeySelectionRenderer(cmbRacikan) {
            @Override
            public String getDisplayValue(Object value) {
                MetodeRacikan racik = (MetodeRacikan) value;
                return racik.getMetode();
            }
        };
    }

//    public void setData(Obat obat) {
//        this.obatResep = new ObatResep(obat.getKodeObat(), obat.getNamaObat(), obat.getSatuan(), obat.getKategori(), obat.getJenisObat(), obat.getStok());
//
//    }
    public ObatResep getData() {
        return this.obatResep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelisi1 = new widget.panelisi();
        label1 = new widget.Label();
        txtJumlah = new widget.TextBox();
        label2 = new widget.Label();
        lblRacikan = new widget.Label();
        cmbRacikan = new widget.ComboBox();
        label4 = new widget.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAturanPakai = new widget.TextArea();
        btnSimpan = new widget.Button();
        button2 = new widget.Button();
        lblObat = new widget.Label();
        txtNamaRacikan = new widget.TextBox();
        comboBox1 = new widget.ComboBox();
        btnAturan = new javax.swing.JButton();
        btnAturan2 = new javax.swing.JButton();
        btnAturan3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelisi1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setText("Jumlah :");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label2.setText("Nama Racikan :");
        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblRacikan.setText("Metode Racikan :");
        lblRacikan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        cmbRacikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRacikanActionPerformed(evt);
            }
        });

        label4.setText("Aturan Pakai :");
        label4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtAturanPakai.setColumns(20);
        txtAturanPakai.setRows(5);
        jScrollPane1.setViewportView(txtAturanPakai);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16i.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        button2.setText("Batal");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        lblObat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObat.setText("Tambah Obat Racikan");
        lblObat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        comboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "30", "60", "90" }));
        comboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox1ActionPerformed(evt);
            }
        });

        btnAturan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAturan.setText("3 dd 1");
        btnAturan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAturan.setPreferredSize(new java.awt.Dimension(37, 15));
        btnAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturanActionPerformed(evt);
            }
        });

        btnAturan2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAturan2.setText("2 dd 1");
        btnAturan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAturan2.setPreferredSize(new java.awt.Dimension(37, 15));
        btnAturan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturan2ActionPerformed(evt);
            }
        });

        btnAturan3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAturan3.setText("1 dd 1");
        btnAturan3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAturan3.setPreferredSize(new java.awt.Dimension(37, 15));
        btnAturan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturan3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelisi1Layout = new javax.swing.GroupLayout(panelisi1);
        panelisi1.setLayout(panelisi1Layout);
        panelisi1Layout.setHorizontalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelisi1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObat, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelisi1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelisi1Layout.createSequentialGroup()
                                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNamaRacikan, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelisi1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelisi1Layout.createSequentialGroup()
                                    .addComponent(lblRacikan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbRacikan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panelisi1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelisi1Layout.createSequentialGroup()
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelisi1Layout.createSequentialGroup()
                                            .addComponent(btnAturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnAturan2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnAturan3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelisi1Layout.setVerticalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelisi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblObat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaRacikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRacikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRacikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAturan2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnAturan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(panelisi1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(panelisi1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        MetodeRacikan metod = (MetodeRacikan) cmbRacikan.getSelectedItem();
        if(isTmp){
            obatResep.setKodeObat("RCKTMP" + countCode);
        obatResep.setKodeRacikan("RCKTMP" + countCode);
        }else{
            obatResep.setKodeObat("RCK" + countCode);
        obatResep.setKodeRacikan("RCK" + countCode);
        }
        
        obatResep.setNomorRacik(countCode);
        obatResep.setMetodeRacikKode(metod.getKode());
        obatResep.setMetodeRacik(metod.getMetode());
        obatResep.setJenisObat(Obat.OBAT_RACIKAN);
        obatResep.setSatuan(metod.getMetode());
        obatResep.setNamaObat(txtNamaRacikan.getText());
        obatResep.setRacikan(txtNamaRacikan.getText());
        obatResep.setJumlah(Integer.parseInt(txtJumlah.getText()));
        obatResep.setAturanPakai(txtAturanPakai.getText());
        obatResep.setEmbalase(0);
        obatResep.setTuslah(0);
        obatResep.setParent(true);
        obatResep.setFlag(true);
        obatResep.setUrutan(countCode);
        obatResep.setEdit(isEdit);
        clean();
        dispose();


    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbRacikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRacikanActionPerformed
        // TODO add your handling code here:
        cmbRacikan = (ComboBox) evt.getSource();
        MetodeRacikan metod = (MetodeRacikan) cmbRacikan.getSelectedItem();
        if (metod != null) {
            obatResep.setKodeObat("RCK" + countCode);
            obatResep.setKodeRacikan("RCK" + countCode);
            obatResep.setMetodeRacikKode(metod.getKode());
            obatResep.setMetodeRacik(metod.getMetode());
            obatResep.setJenisObat("Racikan");
            obatResep.setSatuan(metod.getMetode());
        }
    }//GEN-LAST:event_cmbRacikanActionPerformed

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox1ActionPerformed
        // TODO add your handling code here:
        txtJumlah.setText(comboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_comboBox1ActionPerformed

    private void btnAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturanActionPerformed
        // TODO add your handling code here:
        txtAturanPakai.setText("3 dd 1");
    }//GEN-LAST:event_btnAturanActionPerformed

    private void btnAturan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturan2ActionPerformed
        // TODO add your handling code here:
        txtAturanPakai.setText("2 dd 1");
    }//GEN-LAST:event_btnAturan2ActionPerformed

    private void btnAturan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturan3ActionPerformed
        // TODO add your handling code here:
        txtAturanPakai.setText("1 dd 1");
    }//GEN-LAST:event_btnAturan3ActionPerformed

    void clean() {
        txtJumlah.setText(null);
        txtAturanPakai.setText(null);
        txtNamaRacikan.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogRacikanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogRacikanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogRacikanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogRacikanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRacikanResep dialog = new DialogRacikanResep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAturan;
    private javax.swing.JButton btnAturan2;
    private javax.swing.JButton btnAturan3;
    private widget.Button btnSimpan;
    private widget.Button button2;
    private widget.ComboBox cmbRacikan;
    private widget.ComboBox comboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label4;
    private widget.Label lblObat;
    private widget.Label lblRacikan;
    private widget.panelisi panelisi1;
    private widget.TextArea txtAturanPakai;
    private widget.TextBox txtJumlah;
    private widget.TextBox txtNamaRacikan;
    // End of variables declaration//GEN-END:variables

}
