/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.herinoid.rsi.gui.dialog;

import com.herinoid.rsi.dao.ObatDao;
import com.herinoid.rsi.model.ObatResep;
import com.herinoid.rsi.model.Obat;
import com.herinoid.rsi.table.TabelCariObatResep;
import java.awt.Dimension;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hewrei
 */
public class DlgCariObat extends javax.swing.JDialog {

    private TabelCariObatResep model;
    private TableRowSorter<TabelCariObatResep> rowSorter;
    private ObatResep obatResep;

    /**
     * Creates new form DlgCariObat
     */
    public DlgCariObat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(new Dimension(762, 442));
        model = new TabelCariObatResep();
        txtCari.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtCari.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtCari.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    public void setData(String kodeDepo, String kategoriObat, String jenisPasien) {
        model.removeAllElements();
        if (kategoriObat.equals("K01")) {
            model.add(ObatDao.getObatByCategory(kodeDepo, kategoriObat, jenisPasien));
        } else {
            model.add(ObatDao.getObatByDepo(kodeDepo, jenisPasien));
        }
        tblObat.setModel(model);
        rowSorter = new TableRowSorter<>(model);
        tblObat.setRowSorter(rowSorter);
    }

    public ObatResep getData() {
        return this.obatResep;
    }
    
    public JTable getTable() {
        return tblObat;
    }
    
    public TabelCariObatResep getModel() {
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBiasa1 = new widget.PanelBiasa();
        panelBiasa2 = new widget.PanelBiasa();
        label1 = new widget.Label();
        txtCari = new widget.TextBox();
        scrollPane = new widget.ScrollPane();
        tblObat = new widget.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);

        panelBiasa1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ".:: Cari Data Obat & BHP ::.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        panelBiasa1.setLayout(new java.awt.BorderLayout());

        label1.setText("Cari Data :");
        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBiasa2.add(label1);

        txtCari.setPreferredSize(new java.awt.Dimension(400, 24));
        panelBiasa2.add(txtCari);

        panelBiasa1.add(panelBiasa2, java.awt.BorderLayout.PAGE_START);

        scrollPane.setAutoscrolls(true);

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblObatMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tblObat);

        panelBiasa1.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBiasa1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblObatMouseClicked
        // TODO add your handling code here:
        int selected = tblObat.getSelectedRow();
        if (selected > -1) {
            Obat data = model.get(tblObat.convertRowIndexToModel(selected));
            obatResep = new ObatResep();
            obatResep.setKodeObat(data.getKodeObat());
            obatResep.setNamaObat(data.getNamaObat());
            obatResep.setJumlah(0);
            obatResep.setSatuan(data.getSatuan());
            obatResep.setJenisObat(data.getJenisObat());
            obatResep.setKategori(data.getKategori());
            obatResep.setEmbalase(0);
            obatResep.setTuslah(0);
            obatResep.setStok(data.getStok());
            obatResep.setHarga(data.getHarga());
            dispose();
        }
    }//GEN-LAST:event_tblObatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCariObat dialog = new DlgCariObat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private widget.Label label1;
    private widget.PanelBiasa panelBiasa1;
    private widget.PanelBiasa panelBiasa2;
    private widget.ScrollPane scrollPane;
    private widget.Table tblObat;
    private widget.TextBox txtCari;
    // End of variables declaration//GEN-END:variables

    public void clearData() {
        obatResep = null;
    }
}
